"""Add SQL agent user query history and memory tables

Revision ID: 569b6ec65a8f
Revises: 002_pipeline_coords
Create Date: 2026-01-13 16:56:19.724142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '569b6ec65a8f'
down_revision: Union[str, None] = '002_pipeline_coords'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_conversation_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False, comment='Unique session identifier'),
    sa.Column('session_name', sa.String(length=255), nullable=True, comment='Optional user-defined session name'),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether the session is currently active'),
    sa.Column('context_summary', sa.Text(), nullable=True, comment='Text summary of conversation context for quick retrieval'),
    sa.Column('query_count', sa.Integer(), nullable=False, comment='Number of queries in this session'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_user_active', 'user_conversation_sessions', ['user_id', 'is_active', 'last_activity_at'], unique=False)
    op.create_index('idx_session_user_started', 'user_conversation_sessions', ['user_id', 'started_at'], unique=False)
    op.create_index(op.f('ix_user_conversation_sessions_id'), 'user_conversation_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_user_conversation_sessions_is_active'), 'user_conversation_sessions', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_conversation_sessions_last_activity_at'), 'user_conversation_sessions', ['last_activity_at'], unique=False)
    op.create_index(op.f('ix_user_conversation_sessions_session_id'), 'user_conversation_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_user_conversation_sessions_started_at'), 'user_conversation_sessions', ['started_at'], unique=False)
    op.create_index(op.f('ix_user_conversation_sessions_user_id'), 'user_conversation_sessions', ['user_id'], unique=False)
    op.create_table('user_query_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True, comment='Groups queries into conversation sessions'),
    sa.Column('query_text', sa.Text(), nullable=False, comment="The user's question/query"),
    sa.Column('response_text', sa.Text(), nullable=True, comment="The AI agent's response (may be None if query failed)"),
    sa.Column('query_timestamp', sa.DateTime(), nullable=False),
    sa.Column('response_timestamp', sa.DateTime(), nullable=True, comment='When the response was generated'),
    sa.Column('query_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional metadata: pipeline_ids, tables_queried, SQL generated, etc.'),
    sa.Column('success', sa.Boolean(), nullable=False, comment='Whether the query was successful'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if query failed'),
    sa.Column('processing_time_ms', sa.Float(), nullable=True, comment='Time taken to process query in milliseconds'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_query_session', 'user_query_history', ['session_id', 'query_timestamp'], unique=False)
    op.create_index('idx_query_success', 'user_query_history', ['success', 'query_timestamp'], unique=False)
    op.create_index('idx_query_user_session', 'user_query_history', ['user_id', 'session_id', 'query_timestamp'], unique=False)
    op.create_index('idx_query_user_timestamp', 'user_query_history', ['user_id', 'query_timestamp'], unique=False)
    op.create_index(op.f('ix_user_query_history_id'), 'user_query_history', ['id'], unique=False)
    op.create_index(op.f('ix_user_query_history_query_timestamp'), 'user_query_history', ['query_timestamp'], unique=False)
    op.create_index(op.f('ix_user_query_history_session_id'), 'user_query_history', ['session_id'], unique=False)
    op.create_index(op.f('ix_user_query_history_success'), 'user_query_history', ['success'], unique=False)
    op.create_index(op.f('ix_user_query_history_user_id'), 'user_query_history', ['user_id'], unique=False)
    op.create_table('user_conversation_memory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('memory_type', sa.Enum('FACT', 'PREFERENCE', 'CONTEXT', 'PATTERN', name='memorytype'), nullable=False, comment='Type of memory: fact, preference, context, pattern'),
    sa.Column('memory_key', sa.String(length=255), nullable=False, comment="Key identifier for the memory (e.g., 'user_interests', 'common_queries')"),
    sa.Column('memory_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='The actual memory content (flexible JSON structure)'),
    sa.Column('importance_score', sa.Integer(), nullable=False, comment='Importance score 0-100, determines retention priority'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=False, comment='Last time this memory was used'),
    sa.Column('access_count', sa.Integer(), nullable=False, comment='Number of times this memory has been accessed'),
    sa.Column('expires_at', sa.DateTime(), nullable=True, comment='Optional expiration date for temporary context'),
    sa.Column('source_session_id', sa.String(length=255), nullable=True, comment='Session where this memory was created'),
    sa.Column('source_query_id', sa.Integer(), nullable=True, comment='Query that created this memory'),
    sa.ForeignKeyConstraint(['source_query_id'], ['user_query_history.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_memory_expires', 'user_conversation_memory', ['expires_at'], unique=False)
    op.create_index('idx_memory_user_accessed', 'user_conversation_memory', ['user_id', 'last_accessed_at'], unique=False)
    op.create_index('idx_memory_user_importance', 'user_conversation_memory', ['user_id', 'importance_score', 'last_accessed_at'], unique=False)
    op.create_index('idx_memory_user_key', 'user_conversation_memory', ['user_id', 'memory_key'], unique=False)
    op.create_index('idx_memory_user_type', 'user_conversation_memory', ['user_id', 'memory_type', 'importance_score'], unique=False)
    op.create_index(op.f('ix_user_conversation_memory_created_at'), 'user_conversation_memory', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_conversation_memory_expires_at'), 'user_conversation_memory', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_conversation_memory_id'), 'user_conversation_memory', ['id'], unique=False)
    op.create_index(op.f('ix_user_conversation_memory_importance_score'), 'user_conversation_memory', ['importance_score'], unique=False)
    op.create_index(op.f('ix_user_conversation_memory_last_accessed_at'), 'user_conversation_memory', ['last_accessed_at'], unique=False)
    op.create_index(op.f('ix_user_conversation_memory_memory_key'), 'user_conversation_memory', ['memory_key'], unique=False)
    op.create_index(op.f('ix_user_conversation_memory_memory_type'), 'user_conversation_memory', ['memory_type'], unique=False)
    op.create_index(op.f('ix_user_conversation_memory_user_id'), 'user_conversation_memory', ['user_id'], unique=False)
    op.create_table('user_query_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_history_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Vector embedding stored as JSONB array (or Vector type if pgvector available)'),
    sa.Column('embedding_model', sa.String(length=100), nullable=True, comment="Model used to generate embedding (e.g., 'sentence-transformers/all-MiniLM-L6-v2')"),
    sa.Column('embedding_dimensions', sa.Integer(), nullable=True, comment='Number of dimensions in the embedding vector'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['query_history_id'], ['user_query_history.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_embedding_model', 'user_query_embeddings', ['embedding_model'], unique=False)
    op.create_index('idx_embedding_query', 'user_query_embeddings', ['query_history_id'], unique=False)
    op.create_index('idx_embedding_user', 'user_query_embeddings', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_user_query_embeddings_created_at'), 'user_query_embeddings', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_query_embeddings_id'), 'user_query_embeddings', ['id'], unique=False)
    op.create_index(op.f('ix_user_query_embeddings_query_history_id'), 'user_query_embeddings', ['query_history_id'], unique=True)
    op.create_index(op.f('ix_user_query_embeddings_user_id'), 'user_query_embeddings', ['user_id'], unique=False)
    op.drop_index(op.f('idx_embedding_vector_hnsw'), table_name='identity_embeddings', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_embedding_vector_hnsw'), 'identity_embeddings', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_user_query_embeddings_user_id'), table_name='user_query_embeddings')
    op.drop_index(op.f('ix_user_query_embeddings_query_history_id'), table_name='user_query_embeddings')
    op.drop_index(op.f('ix_user_query_embeddings_id'), table_name='user_query_embeddings')
    op.drop_index(op.f('ix_user_query_embeddings_created_at'), table_name='user_query_embeddings')
    op.drop_index('idx_embedding_user', table_name='user_query_embeddings')
    op.drop_index('idx_embedding_query', table_name='user_query_embeddings')
    op.drop_index('idx_embedding_model', table_name='user_query_embeddings')
    op.drop_table('user_query_embeddings')
    op.drop_index(op.f('ix_user_conversation_memory_user_id'), table_name='user_conversation_memory')
    op.drop_index(op.f('ix_user_conversation_memory_memory_type'), table_name='user_conversation_memory')
    op.drop_index(op.f('ix_user_conversation_memory_memory_key'), table_name='user_conversation_memory')
    op.drop_index(op.f('ix_user_conversation_memory_last_accessed_at'), table_name='user_conversation_memory')
    op.drop_index(op.f('ix_user_conversation_memory_importance_score'), table_name='user_conversation_memory')
    op.drop_index(op.f('ix_user_conversation_memory_id'), table_name='user_conversation_memory')
    op.drop_index(op.f('ix_user_conversation_memory_expires_at'), table_name='user_conversation_memory')
    op.drop_index(op.f('ix_user_conversation_memory_created_at'), table_name='user_conversation_memory')
    op.drop_index('idx_memory_user_type', table_name='user_conversation_memory')
    op.drop_index('idx_memory_user_key', table_name='user_conversation_memory')
    op.drop_index('idx_memory_user_importance', table_name='user_conversation_memory')
    op.drop_index('idx_memory_user_accessed', table_name='user_conversation_memory')
    op.drop_index('idx_memory_expires', table_name='user_conversation_memory')
    op.drop_table('user_conversation_memory')
    op.drop_index(op.f('ix_user_query_history_user_id'), table_name='user_query_history')
    op.drop_index(op.f('ix_user_query_history_success'), table_name='user_query_history')
    op.drop_index(op.f('ix_user_query_history_session_id'), table_name='user_query_history')
    op.drop_index(op.f('ix_user_query_history_query_timestamp'), table_name='user_query_history')
    op.drop_index(op.f('ix_user_query_history_id'), table_name='user_query_history')
    op.drop_index('idx_query_user_timestamp', table_name='user_query_history')
    op.drop_index('idx_query_user_session', table_name='user_query_history')
    op.drop_index('idx_query_success', table_name='user_query_history')
    op.drop_index('idx_query_session', table_name='user_query_history')
    op.drop_table('user_query_history')
    op.drop_index(op.f('ix_user_conversation_sessions_user_id'), table_name='user_conversation_sessions')
    op.drop_index(op.f('ix_user_conversation_sessions_started_at'), table_name='user_conversation_sessions')
    op.drop_index(op.f('ix_user_conversation_sessions_session_id'), table_name='user_conversation_sessions')
    op.drop_index(op.f('ix_user_conversation_sessions_last_activity_at'), table_name='user_conversation_sessions')
    op.drop_index(op.f('ix_user_conversation_sessions_is_active'), table_name='user_conversation_sessions')
    op.drop_index(op.f('ix_user_conversation_sessions_id'), table_name='user_conversation_sessions')
    op.drop_index('idx_session_user_started', table_name='user_conversation_sessions')
    op.drop_index('idx_session_user_active', table_name='user_conversation_sessions')
    op.drop_table('user_conversation_sessions')
    # ### end Alembic commands ###
