# ---------------------------------------------------------------------------
# THE deployment path manifest — one table, every host path the stack touches.
#
# Why this file exists
# --------------------
# Ownership and modes were being set in four different places (deploy.sh stage
# 03, generate-secrets.sh, fix-permissions.sh, and whatever ran first), so the
# same tree ended up with:
#
#     secrets  700 root:root      storage  775 itdirect-ai
#     certs    755 root:root      backups  755 root:root
#
# and `storage`, `database` and `logs` were created by nobody in particular —
# they existed only because an earlier run happened to make them. Three
# separate production failures came out of that on the first real deployment:
#
#   * secrets 0600 root  -> uid-1000 containers got PermissionError, the
#     config preflight failed closed, and migrate refused to run
#   * secrets 0640       -> the preflight refused the WRITE bit on a mounted
#     secret
#   * users.acl 0600 root-> redis could not read its own ACL and crash-looped,
#     which silently blocked the whole app tier (face_recognition waits on
#     redis being healthy)
#
# The rule that resolves all three:
#
#   A path a container WRITES  -> owned by the service uid (1000)
#   A path a container READS   -> readable by the service GID, never writable
#   A secret                   -> 0440 root:1000 (readable, never writable)
#   A host-only path           -> root, mode as tight as the tooling allows
#
# Columns:  path | mode | owner:group | what it is
#
# `docker compose` bind-mounts PRESERVE host ownership (this is not swarm, so
# the `secrets:` block is a bind, not a tmpfs), which is why the host modes
# here are load-bearing rather than cosmetic.
# ---------------------------------------------------------------------------

# Service uid/gid: face_recognition, ml_worker and migrate run as 1000:1000
# (see the `user:` key in docker-compose.prod.yml). Every readable-by-container
# path is grouped to 1000 so it works regardless of the host account's own uid.
SVC_UID=1000
SVC_GID=1000

# path                  mode  owner        purpose
DEPLOY_PATHS=(
  # 0750 root:1000, not 0700 root:root: group 1000 may TRAVERSE the directory,
  # so the host user can read a secret without sudo. The FILES inside stay
  # 0440 root:1000 - readable, never writable. This grants nothing new, since
  # uid 1000 is in the docker group and that is already root-equivalent.
  "secrets              0750  root:1000    host dir; the FILES inside are 0440 root:1000"
  "certs                0755  root:root    TLS; server.key stays 0600, CA cert is world-readable"
  "weights              0755  root:1000    ONNX models, read-only to face_recognition"
  "map-data/production  0755  root:1000    .mbtiles + fonts, read-only to martin"
  "map-data/metadata    0755  root:1000    checksums + dataset catalogue"
  "docker/redis         0755  root:root    holds users.acl, which is 0640 999:1000"
  # NOTE — storage, logs and database below are mounted by the DEVELOPMENT
  # stack (docker-compose.cpu.yml binds them from the host). PRODUCTION mounts
  # named volumes instead (storage_data, logs_data, face_database_data), so in
  # a production deployment these host directories stay empty by design. That
  # is why `docker compose up` appears not to "generate" them: nothing writes
  # here. They are still created and owned so the dev stack works and so a
  # bind-mount deployment has a correct target.
  "storage              0775  1000:1000    face crops and artifacts — WRITTEN by the app"
  "logs                 0775  1000:1000    application logs — WRITTEN by the app"
  "logs/deploy          0775  1000:1000    deploy.sh run logs"
  "database             0775  1000:1000    local index files — WRITTEN by the app"
  "backups              0750  root:root    pg_dump output; host-only by design"
  ".deployment          0700  root:root    deploy state; host-only by design"
)

# Files whose mode matters individually (a directory mode cannot express these).
DEPLOY_FILES=(
  "secrets/jwt_secret               0440  root:1000  read by face_recognition + migrate"
  "secrets/bootstrap_admin_password 0440  root:1000  read by face_recognition"
  "secrets/webhook_api_keys         0440  root:1000  read by face_recognition + migrate"
  "docker/redis/users.acl           0640  999:1000   read by redis (uid 999 in redis:7-alpine)"
  # Written by stage-gpu.sh running as root, so without an entry here it stayed
  # root-owned and was the only file in the repo the host user could not edit.
  "docker/gpu-allocation.generated.yml 0644 1000:1000 GPU UUID overlay, a third compose file"
  # Generated by the map ledger verification, which runs as root in a
  # throwaway container and leaves the file 0600 root:root - unreadable to the
  # uid-1000 service. The API then reports every basemap UNAVAILABLE with no
  # error of its own, because fail-closed is working exactly as designed.
  "map-data/metadata/content_verdicts.json 0664 1000:1000 which archives passed content verification"
  "docker/.env                      0600  root:root  compose reads it as root; no container mounts it"
  "certs/server.key                 0600  root:root  private key, host-only"
  "certs/internal-ca.key            0600  root:root  CA private key — move OFFLINE after issuing"
  "certs/server.crt                 0644  root:root  public cert"
  "certs/internal-ca.crt            0644  root:root  public cert, distributed to clients"
)

# apply_deployment_paths: make reality match the table. Idempotent.
apply_deployment_paths() {
    local entry path mode owner
    for entry in "${DEPLOY_PATHS[@]}"; do
        read -r path mode owner _ <<< "$entry"
        [ -d "$ROOT/$path" ] || mkdir -p "$ROOT/$path"
        chmod "$mode" "$ROOT/$path" 2>/dev/null || true
        chown "$owner" "$ROOT/$path" 2>/dev/null || true
    done
    for entry in "${DEPLOY_FILES[@]}"; do
        read -r path mode owner _ <<< "$entry"
        [ -e "$ROOT/$path" ] || continue     # generated later by another stage
        chmod "$mode" "$ROOT/$path" 2>/dev/null || true
        chown "$owner" "$ROOT/$path" 2>/dev/null || true
    done
}

# verify_deployment_paths: report drift WITHOUT changing anything.
# Returns 0 when every path matches, 1 otherwise. Used by `./deploy.sh paths`.
verify_deployment_paths() {
    local entry path mode owner want_mode got_mode got_owner problems=0 label
    printf '  %-38s %-6s %-12s %s\n' "PATH" "MODE" "OWNER" "STATUS"
    for entry in "${DEPLOY_PATHS[@]}" "${DEPLOY_FILES[@]}"; do
        read -r path mode owner _ <<< "$entry"
        want_mode="${mode#0}"
        if [ ! -e "$ROOT/$path" ]; then
            # A path inside a 0700 root dir is unreadable to a normal user —
            # that is not the same as absent, and reporting MISSING sends
            # someone hunting for a file that is sitting right there.
            if [ "$(id -u)" != "0" ] && [ ! -r "$(dirname "$ROOT/$path")" ]; then
                printf '  %-38s %-6s %-12s ? (needs sudo to check)\n' "$path" "$mode" "$owner"
            else
                printf '  %-38s %-6s %-12s MISSING\n' "$path" "$mode" "$owner"
                problems=$((problems + 1))
            fi
            continue
        fi
        got_mode="$(stat -c%a "$ROOT/$path" 2>/dev/null)"
        got_owner="$(stat -c%u:%g "$ROOT/$path" 2>/dev/null)"
        # Compare numerically: the host account name for uid 1000 varies, and
        # uid 999 shows up under whatever system account happens to hold it.
        local want_owner="$owner"
        case "$owner" in root:root) want_owner="0:0" ;; root:1000) want_owner="0:1000" ;;
                         1000:1000) want_owner="1000:1000" ;; 999:1000) want_owner="999:1000" ;; esac
        if [ "$got_mode" = "$want_mode" ] && [ "$got_owner" = "$want_owner" ]; then
            label="ok"
        else
            label="DRIFT (is ${got_mode} ${got_owner})"; problems=$((problems + 1))
        fi
        printf '  %-38s %-6s %-12s %s\n' "$path" "$mode" "$owner" "$label"
    done
    return $([ "$problems" -eq 0 ] && echo 0 || echo 1)
}
