#!/usr/bin/env bash
#
# Stage 07 — GPU detection, allocation and proof.
#
# What actually uses a GPU in this system:
#   face_recognition  SCRFD + ArcFace ONNX sessions. WORKERS=1 is mandatory
#                     (process-local state), so it is ONE CUDA session and a
#                     second card buys it nothing.
#   ollama            the chat/SQL LLMs. Optional; the face pipeline is
#                     unaffected when it is absent or on CPU.
# Nothing else. No YOLO, no LPR, no vehicle models, no TensorRT exist in this
# codebase — person boxes arrive from the external VMS over webhooks.
#
# Allocation (override with --gpu-ids=a[,b], persisted as GPU_IDS):
#   1 GPU   face_recognition and ollama share it (VRAM is checked and warned)
#   2 GPUs  face_recognition -> GPU A, ollama -> GPU B
#   3+      as above; the remainder is reported as unassigned, never handed
#           out "just in case" (the brief: do not expose every GPU to every
#           container).
#
# Assignment is expressed as a generated compose overlay using GPU **UUIDs**,
# which survive reboots and PCI reordering in a way indexes do not.

NVIDIA_SMI="${NVIDIA_SMI:-nvidia-smi}"

# gpu_inventory: "index|uuid|name|vram_mib" per line. Empty when no GPU.
gpu_inventory() {
    have "$NVIDIA_SMI" || return 0
    "$NVIDIA_SMI" --query-gpu=index,uuid,name,memory.total --format=csv,noheader,nounits 2>/dev/null \
        | sed 's/, */|/g' | sed 's/[[:space:]]*$//'
}

# render_gpu_overlay: the whole file, deterministic for a given assignment.
#
# `!override` matters: the base GPU file already declares a
# `devices: [{driver: nvidia, count: 1, ...}]` reservation, and compose MERGES
# list items — without the tag the container would end up with both entries.
render_gpu_overlay() {
    local api_uuid="$1" ollama_uuid="${2:-}"
    # Computed before the heredoc: a ${var:-default} whose default contains
    # angle brackets is not a substitution bash will parse there.
    local ollama_display="$ollama_uuid"
    [ -n "$ollama_display" ] || ollama_display="(shares the face_recognition GPU)"
    local stamp; stamp="$(timestamp)"
    cat <<EOF
# GENERATED by deploy.sh — do not edit; regenerated on every run.
#
# Host-specific GPU assignment, layered as a third -f file on top of
# docker-compose.prod.yml and docker-compose.prod.gpu.yml. UUIDs (not indexes)
# so a reboot or PCI reordering cannot silently move a workload to another card.
#
#   generated_at: ${stamp}
#   face_recognition -> ${api_uuid}
#   ollama           -> ${ollama_display}
services:
  face_recognition:
    environment:
      # One process, one CUDA session. Raising this breaks correctness
      # (process-local caches/single-flight guards), not just performance.
      WORKERS: "1"
    deploy:
      resources:
        reservations:
          devices: !override
            - driver: nvidia
              device_ids: ["${api_uuid}"]
              capabilities: [gpu]
EOF
    if [ -n "$ollama_uuid" ]; then
        cat <<EOF
  ollama:
    deploy:
      resources:
        reservations:
          devices: !override
            - driver: nvidia
              device_ids: ["${ollama_uuid}"]
              capabilities: [gpu]
EOF
    fi
}

# uuid_for_index: resolve an nvidia-smi index to its stable UUID.
uuid_for_index() {
    local want="$1"
    gpu_inventory | while IFS='|' read -r idx uuid _name _vram; do
        [ "$idx" = "$want" ] && { printf '%s' "$uuid"; return 0; }
    done
}

stage_gpu_detect() {
    stage_begin "07 GPU detection and allocation"
    explain "WHAT" "Inventories the GPUs and pins each service to specific cards."
    explain "READS" "nvidia-smi --query-gpu=index,uuid,name,memory.total"
    explain "WRITES" "docker/gpu-allocation.generated.yml - a third compose file layered"
    explain_cont "over the base and the GPU overlay. Pins by UUID, not index, so a"
    explain_cont "reboot or PCI reordering cannot move a workload onto another card."
    explain_cont "docker/.env GPU_IDS, when you passed --gpu-ids."
    explain_cont "Gitignored: it describes THIS host and must not follow the repo."
    explain "FAIL" "the merged config does not carry the intended device ids, i.e. the"
    explain_cont "overlay appended instead of overriding. Verified BEFORE any container"
    explain_cont "starts, because the alternative is learning it from a wrong card."

    if [ "$FORCE_CPU" = "1" ]; then
        GPU_MODE=0; export GPU_MODE
        state_set gpu_assignment "cpu (--cpu)"
        stage_pass "CPU mode requested — no GPU overlay"
        return 0
    fi

    # ---- detect -----------------------------------------------------------
    local inventory count
    inventory="$(gpu_inventory)"
    count="$(printf '%s' "$inventory" | grep -c '|' || true)"
    [ -n "$inventory" ] || count=0

    if [ "$count" -eq 0 ]; then
        GPU_MODE=0; export GPU_MODE
        state_set gpu_assignment "cpu (no NVIDIA GPU detected)"
        # Not a failure: a CPU deployment is fully supported and the base
        # compose file runs unchanged.
        stage_warn "no NVIDIA GPU detected — deploying in CPU mode (ALLOW_CPU_FALLBACK stays at the base default)"
        return 0
    fi

    printf '%s\n' "$inventory" | while IFS='|' read -r idx uuid name vram; do
        info "GPU $idx: $name, ${vram} MiB, $uuid"
    done

    # ---- allocate ---------------------------------------------------------
    local requested="${GPU_IDS_FLAG:-$(read_env_kv GPU_IDS 2>/dev/null)}"
    local api_idx ollama_idx="" spare=""
    if [ -n "$requested" ]; then
        api_idx="${requested%%,*}"
        local rest="${requested#*,}"
        [ "$rest" != "$requested" ] && ollama_idx="${rest%%,*}"
        info "explicit assignment requested: GPU_IDS=$requested"
        gpu_inventory | grep -q "^${api_idx}|" || stage_fail "GPU_IDS names index $api_idx, which this host does not have"
        if [ -n "$ollama_idx" ]; then
            gpu_inventory | grep -q "^${ollama_idx}|" || stage_fail "GPU_IDS names index $ollama_idx, which this host does not have"
        fi
    else
        api_idx="$(printf '%s\n' "$inventory" | head -1 | cut -d'|' -f1)"
        if [ "$count" -ge 2 ]; then
            ollama_idx="$(printf '%s\n' "$inventory" | sed -n '2p' | cut -d'|' -f1)"
        fi
        [ "$count" -ge 3 ] && spare="$(printf '%s\n' "$inventory" | tail -n +3 | cut -d'|' -f1 | tr '\n' ',' | sed 's/,$//')"
    fi

    local api_uuid ollama_uuid=""
    api_uuid="$(uuid_for_index "$api_idx")"
    [ -n "$api_uuid" ] || stage_fail "could not resolve a UUID for GPU index $api_idx"
    if [ -n "$ollama_idx" ]; then
        ollama_uuid="$(uuid_for_index "$ollama_idx")"
        [ -n "$ollama_uuid" ] || stage_fail "could not resolve a UUID for GPU index $ollama_idx"
    fi

    info "face_recognition -> GPU $api_idx"
    if [ -n "$ollama_idx" ]; then
        info "ollama           -> GPU $ollama_idx"
    else
        local vram; vram="$(printf '%s\n' "$inventory" | head -1 | cut -d'|' -f4)"
        info "ollama           -> shares GPU $api_idx"
        if [ -n "$vram" ] && [ "$vram" -lt 16000 ] 2>/dev/null; then
            stage_warn "single GPU with ${vram} MiB shared by the ONNX sessions and a 7B Q4 LLM — if ollama OOMs, run it on CPU or add a second card"
        fi
    fi
    [ -n "$spare" ] && info "GPU(s) $spare: unassigned and available (nothing in this system can use a third card)"

    # ---- apply ------------------------------------------------------------
    GPU_MODE=1; export GPU_MODE
    local assignment="face_recognition=GPU${api_idx}"
    [ -n "$ollama_idx" ] && assignment="$assignment ollama=GPU${ollama_idx}" || assignment="$assignment ollama=shared"
    [ -n "$spare" ] && assignment="$assignment spare=${spare}"

    if [ "${VALIDATE_ONLY:-0}" = "1" ] || [ "$DRY_RUN" = "1" ]; then
        info "would write $(basename "$GPU_OVERLAY")"
    else
        render_gpu_overlay "$api_uuid" "$ollama_uuid" > "$GPU_OVERLAY" || stage_fail "could not write $GPU_OVERLAY"
        [ -n "$requested" ] && upsert_env_kv GPU_IDS "$requested"
        state_set gpu_assignment "$assignment"
    fi

    # ---- verify: the generated file must actually compose ------------------
    # Done BEFORE any container starts: an overlay that merges wrongly would
    # otherwise be discovered by a container silently running on the wrong card.
    local rendered
    if ! rendered="$(compose config 2>&1)"; then
        stage_fail "the generated GPU overlay does not compose: $rendered"
    fi
    if [ "$DRY_RUN" != "1" ] && [ "${VALIDATE_ONLY:-0}" != "1" ]; then
        printf '%s' "$rendered" | grep -q "$api_uuid" || \
            stage_fail "the merged configuration does not carry the intended device id for face_recognition"
        local device_lines
        device_lines="$(printf '%s' "$rendered" | grep -c 'device_ids' || true)"
        local expected=1; [ -n "$ollama_uuid" ] && expected=2
        [ "$device_lines" = "$expected" ] || \
            stage_fail "merged configuration has $device_lines device_ids entries, expected $expected (compose merge appended instead of overriding)"
    fi

    # One CUDA session per process. The single-flight guards and model caches
    # are process-local, so a second worker is a correctness bug, not a
    # throughput setting — assert it on the MERGED config, where an overlay
    # could have raised it.
    local workers
    workers="$(merged_env_value "$rendered" face_recognition WORKERS)"
    [ "$workers" = "1" ] || stage_fail \
        "face_recognition resolves to WORKERS=${workers:-<unset>}; the GPU service must run exactly one process"

    stage_pass "$count GPU(s); $assignment"
}

# Quiet variant for subcommands that only need to know whether the GPU overlay
# applies (health, status) without re-deciding or rewriting anything.
stage_gpu_detect_quiet() {
    if [ "$FORCE_CPU" = "1" ]; then GPU_MODE=0; export GPU_MODE; return 0; fi
    if [ -f "$GPU_OVERLAY" ] && [ -n "$(gpu_inventory)" ]; then GPU_MODE=1; else GPU_MODE=0; fi
    export GPU_MODE
}

# ---------------------------------------------------------------------------
# Stage — gpu-test: the full chain, each link proved separately.
#
#   host driver -> container toolkit -> CUDA in a container -> onnxruntime
#   CUDA provider -> the REAL SCRFD and ArcFace models -> an actual inference
#
# nvidia-smi answering is the first link, never the proof.
# ---------------------------------------------------------------------------
stage_gpu_test() {
    stage_begin "GPU acceptance"
    explain "WHAT" "Proves CUDA end to end: driver, toolkit, container, real inference."
    explain "READS" "weights/det_10g.onnx and weights/w600k_r50.onnx, on a real image."
    explain "WRITES" "nothing."
    explain "FAIL" "nvidia-smi alone is NOT sufficient here. If SCRFD or ArcFace load on"
    explain_cont "CPUExecutionProvider this fails deliberately: a silent CPU fallback"
    explain_cont "looks healthy while serving a fraction of the throughput."

    if [ "${GPU_MODE:-0}" != "1" ]; then
        stage_skip "CPU deployment — no GPU acceptance to run"
        return 0
    fi

    # 1. host driver
    "$NVIDIA_SMI" >/dev/null 2>&1 || stage_fail "nvidia-smi does not answer on the host"
    local driver; driver="$("$NVIDIA_SMI" --query-gpu=driver_version --format=csv,noheader | head -1)"
    ok "host driver $driver"

    # 2+3. container toolkit and CUDA inside a container, on the CUDA
    # generation this stack actually builds against (12.4).
    if [ "$DRY_RUN" = "1" ]; then
        info "DRY: docker run --rm --gpus all nvidia/cuda:12.4.1-base-ubuntu22.04 nvidia-smi"
    elif docker run --rm --gpus all nvidia/cuda:12.4.1-base-ubuntu22.04 nvidia-smi >/dev/null 2>&1; then
        ok "container toolkit: CUDA 12.4 container sees the GPU"
    else
        stage_fail "docker cannot expose the GPU to a container (nvidia-container-toolkit / 'nvidia-ctk runtime configure --runtime=docker' then restart docker)"
    fi

    # 4+5+6. onnxruntime CUDA provider AND a real inference with the deployed
    # SCRFD + ArcFace weights, inside the running API container.
    if ! compose ps --status running --format '{{.Service}}' 2>/dev/null | grep -q '^face_recognition$'; then
        stage_warn "API container is not running — start the stack to complete the GPU acceptance (driver and toolkit verified)"
        return 0
    fi
    real_inference_test gpu || stage_fail "real GPU inference failed — see the output above"
    stage_pass "driver -> toolkit -> CUDA -> onnxruntime -> SCRFD + ArcFace inference on CUDA"
}

# ---------------------------------------------------------------------------
# real_inference_test <gpu|cpu>
#
# One REAL detection and one REAL embedding on a committed fixture face, in
# the running container, using the deployed weights. This is the check that a
# CPU fallback cannot pass: in GPU mode it asserts the session's first
# provider is CUDAExecutionProvider, which is what "the model is actually on
# the GPU" means. A zero-tensor smoke test would pass with the wrong weights;
# a provider list alone would pass on CPU.
# ---------------------------------------------------------------------------
real_inference_test() {
    local mode="${1:-cpu}"
    if [ "$DRY_RUN" = "1" ]; then
        info "DRY: real inference test (${mode})"
        return 0
    fi
    local script output
    script=$(cat <<'PY'
import sys
import cv2
from backend.core import model_manager

REQUIRE_CUDA = sys.argv[1] == "gpu"
IMAGE = "/app/tests/fixtures/faces/face_a.jpg"

model_manager.initialize()
img = cv2.imread(IMAGE)
if img is None:
    print("FAIL fixture image unreadable:", IMAGE); sys.exit(1)

det, kpss = model_manager.detector.detect(img, max_num=1)
if len(det) != 1:
    print("FAIL expected exactly 1 face, got", len(det)); sys.exit(1)

emb = model_manager.recognizer.get_embedding(img, kpss[0])
if tuple(emb.shape) != (512,):
    print("FAIL embedding shape", emb.shape); sys.exit(1)

det_providers = model_manager.detector.session.get_providers()
rec_providers = model_manager.recognizer.session.get_providers()
print("detector providers:", det_providers)
print("recognizer providers:", rec_providers)
print("score: %.4f  embedding: %s" % (float(det[0][4]), tuple(emb.shape)))

if REQUIRE_CUDA:
    for name, providers in (("SCRFD", det_providers), ("ArcFace", rec_providers)):
        if not providers or providers[0] != "CUDAExecutionProvider":
            print("FAIL %s is NOT running on CUDA (providers=%s) - this is the silent "
                  "CPU fallback the deployment must never accept" % (name, providers))
            sys.exit(1)
    print("OK both models executed on CUDA")
else:
    print("OK inference succeeded (CPU deployment)")
PY
)
    if output="$(compose exec -T face_recognition python -c "$script" "$mode" 2>&1)"; then
        printf '%s\n' "$output" | sed 's/^/     /'
        return 0
    fi
    printf '%s\n' "$output" | sed 's/^/     /' >&2
    return 1
}
