#!/usr/bin/env bash
#
# Generate every production secret this deployment needs.
#
#   bash scripts/setup/generate-secrets.sh
#
# Writes Docker secret files under secrets/, the Redis ACL under
# docker/redis/users.acl, and prints the .env lines to add. Both directories are
# gitignored. Existing files are never overwritten — delete them deliberately to
# rotate.
#
# Rotating JWT_SECRET_KEY invalidates every issued token, logging everyone out.
# That is intended.

set -euo pipefail

cd "$(dirname "$0")/../.."

SECRETS_DIR="secrets"
ACL_DIR="docker/redis"
ACL_FILE="${ACL_DIR}/users.acl"

mkdir -p "$SECRETS_DIR" "$ACL_DIR"

if ! command -v openssl >/dev/null 2>&1; then
    echo "openssl is required" >&2
    exit 1
fi

# Two generators, deliberately.
#
# gen_b64 is for secrets that are read as opaque strings — the JWT key and the
# bootstrap password. 48 bytes of base64 keeps the signing key well above
# HS256's useful key size.
gen_b64() { openssl rand -base64 "${1:-32}" | tr -d '\n'; }

# gen_url is for anything embedded in a connection URL. base64 emits '/', '+'
# and '=', and a '/' in a password makes urlsplit parse the URL completely
# differently: in redis://fr_app:aB3/xY9@redis:6379/0 the host becomes "fr_app"
# and the password becomes None, so the application connects nowhere. Hex has
# no reserved characters, so no URL-encoding is required anywhere downstream.
gen_url() { openssl rand -hex "${1:-24}" | tr -d '\n'; }

sha256_hex() { printf '%s' "$1" | openssl dgst -sha256 | awk '{print $NF}'; }

write_secret() {
    local name="$1" value="$2" path="${SECRETS_DIR}/$1"
    if [ -f "$path" ]; then
        echo "  = ${path} already exists, keeping it"
        return
    fi
    printf '%s' "$value" > "$path"
    chmod 600 "$path" 2>/dev/null || true
    echo "  + ${path}"
}

echo "Generating Docker secret files..."
# Never embedded in a URL, so base64 is fine and gives more entropy per byte.
write_secret jwt_secret "$(gen_b64 48)"
write_secret bootstrap_admin_password "$(gen_b64 24)"
# The break-glass ingest key. docker-compose.prod.yml and .gpu.yml both declare
# secrets/webhook_api_keys as a required secret FILE, so without this line a
# clean deploy that follows the runbook in order fails at `docker compose up`.
# gen_b64, not gen_url: it is never embedded in a URL, and the base64 alphabet
# contains no comma, so parse_keys() can never silently split one generated key
# into two weak halves. Per-sender credentials are minted afterwards from
# Admin > Ingest Credentials; this one stays as the break-glass path.
write_secret webhook_api_keys "$(gen_b64 48)"

# These ARE embedded in connection URLs by compose, so they must be URL-safe.
FR_APP_PASSWORD="$(gen_url 24)"
FR_MIGRATOR_PASSWORD="$(gen_url 24)"
FR_READONLY_PASSWORD="$(gen_url 24)"
FR_BACKUP_PASSWORD="$(gen_url 24)"
POSTGRES_SUPERUSER_PASSWORD="$(gen_url 24)"
REDIS_PASSWORD="$(gen_url 24)"
REDIS_MONITOR_PASSWORD="$(gen_url 24)"

echo
echo "Generating Redis ACL..."
if [ -f "$ACL_FILE" ]; then
    echo "  = ${ACL_FILE} already exists, keeping it (delete it to rotate)"
else
    sed -e "s/#REPLACE_WITH_SHA256_HEX/#$(sha256_hex "$REDIS_PASSWORD")/" \
        -e "s/#REPLACE_WITH_MONITOR_SHA256_HEX/#$(sha256_hex "$REDIS_MONITOR_PASSWORD")/" \
        "${ACL_DIR}/users.acl.example" > "$ACL_FILE"
    chmod 600 "$ACL_FILE" 2>/dev/null || true
    echo "  + ${ACL_FILE}"
fi

# ---------------------------------------------------------------------------
# docker/.env — the file Compose ACTUALLY reads
#
# Compose reads .env from the PROJECT DIRECTORY, which is the directory of the
# first -f file: docker/. The repository-root .env is never consulted for
# ${VAR} substitution. Printing these for the operator to paste into the root
# .env — which is what this script used to do — produced a deployment that
# still failed on "POSTGRES_SUPERUSER_PASSWORD is required", with the operator
# looking at a file that plainly contained it.
#
# Root .env stays the APPLICATION config (read by pydantic inside the
# process). docker/.env is DEPLOYMENT credentials for interpolation only.
#
# Never overwritten: re-running must not silently re-key a live deployment.
# The script cd'd to the repository root at line 17, so this is relative to it,
# exactly like SECRETS_DIR and ACL_DIR above.
COMPOSE_ENV="docker/.env"
if [ -f "$COMPOSE_ENV" ]; then
    echo "  = ${COMPOSE_ENV} (exists, left untouched)"
    WROTE_COMPOSE_ENV=0
else
    umask 077
    cat > "$COMPOSE_ENV" <<EOF
# Generated by scripts/setup/generate-secrets.sh — DEPLOYMENT credentials.
# Read by Docker Compose for \${VAR} substitution ONLY; never injected into a
# container. Application settings live in the repository-root .env.
# Not in version control. Delete a line and re-run the generator to rotate it.

PUBLIC_ORIGIN=https://face-detector.internal

POSTGRES_SUPERUSER_PASSWORD=${POSTGRES_SUPERUSER_PASSWORD}
FR_APP_PASSWORD=${FR_APP_PASSWORD}
FR_MIGRATOR_PASSWORD=${FR_MIGRATOR_PASSWORD}
FR_READONLY_PASSWORD=${FR_READONLY_PASSWORD}
FR_BACKUP_PASSWORD=${FR_BACKUP_PASSWORD}
REDIS_PASSWORD=${REDIS_PASSWORD}
REDIS_MONITOR_PASSWORD=${REDIS_MONITOR_PASSWORD}
GRAFANA_ADMIN_PASSWORD=$(gen_url 24)
EOF
    chmod 600 "$COMPOSE_ENV" 2>/dev/null || true
    echo "  + ${COMPOSE_ENV}"
    WROTE_COMPOSE_ENV=1
fi

# ---------------------------------------------------------------------------
# Credential FILES for the containers, derived from docker/.env
#
# Compose used to embed these in `environment:` (DATABASE_URL with the password
# inline, POSTGRES_PASSWORD, REDIS_URL, SQL_AGENT_DB_PASSWORD, PGPASSWORD), so
# every one of them was readable via `docker inspect`. config.py already
# resolves *_FILE variants for all of them; compose now mounts these instead.
#
# Read back from docker/.env rather than from this run's variables: on an
# EXISTING deployment the variables above are fresh random values that do not
# match the live database, while docker/.env is what the roles were created
# with. Deriving from the file is correct on a fresh install and a re-run alike.
# write_secret never overwrites, so re-running cannot re-key a live deployment.
# ---------------------------------------------------------------------------
echo
echo "Generating credential files from ${COMPOSE_ENV}..."
env_value() { grep "^$1=" "$COMPOSE_ENV" | head -1 | cut -d= -f2-; }
_app="$(env_value FR_APP_PASSWORD)"; _mig="$(env_value FR_MIGRATOR_PASSWORD)"
_ro="$(env_value FR_READONLY_PASSWORD)"; _bk="$(env_value FR_BACKUP_PASSWORD)"
_rp="$(env_value REDIS_PASSWORD)"
if [ -z "$_app" ] || [ -z "$_mig" ] || [ -z "$_ro" ] || [ -z "$_bk" ] || [ -z "$_rp" ]; then
    echo "  ! ${COMPOSE_ENV} is missing a password; credential files not written" >&2
else
    write_secret database_url_app       "postgresql+asyncpg://fr_app:${_app}@postgres:5432/face_recognition"
    write_secret database_url_migrator  "postgresql+asyncpg://fr_migrator:${_mig}@postgres:5432/face_recognition"
    write_secret postgres_password_app       "$_app"
    write_secret postgres_password_migrator  "$_mig"
    write_secret redis_url              "redis://fr_app:${_rp}@redis:6379/0"
    write_secret sql_agent_db_password  "$_ro"
    write_secret backup_db_password     "$_bk"
fi
unset _app _mig _ro _bk _rp

cat <<EOF

------------------------------------------------------------------------
Deployment credentials are in docker/.env (mode 600, gitignored).
Compose reads that file automatically — nothing to paste.
$( [ "$WROTE_COMPOSE_ENV" = "0" ] && echo "NOTE: docker/.env already existed and was NOT modified. If you need to
rotate a credential, delete its line and re-run this script." )
------------------------------------------------------------------------

Next:
  1. Apply the database roles:  psql -f db/roles.sql   (see the header there)
  2. Generate TLS material:     bash scripts/tls/make-internal-ca.sh
  3. Verify the configuration:  docker compose -f docker/docker-compose.prod.yml config -q

Back up docker/.env and secrets/ somewhere safe: losing them locks you out of
your own database.
EOF
