#!/usr/bin/env python3
"""Generate Docs/47_API_INDEX.md: every HTTP/WebSocket route with its handler,
auth dependencies, whether it writes to the database, whether it audits, and
the first line of its docstring. Pure AST — nothing is imported or executed.

    python3 scripts/generate_api_index.py > Docs/47_API_INDEX.md
"""
import ast, sys, re, io, glob
WRITE = re.compile(r"\b(db|session|_db)\.(add|delete|merge|execute)\(|\.commit\(\)|update\(|insert\(|delete\(", re.I)
def deps(node):
    out=[]
    for a in node.args.args + node.args.kwonlyargs:
        pass
    for d in node.args.defaults + node.args.kw_defaults:
        if d is None: continue
        s = ast.unparse(d)
        if 'Depends(' in s: out.append(s.replace('Depends(','').rstrip(')')[:60])
    return out
print('# 99a — API index (generated by scripts/generate_api_index.py)\n\nColumns: METHOD path handler [read|WRITE][ audit] deps=[auth/db dependencies]; second line = docstring. `WRITE` = the handler changes the database. Paths are as declared on the router (see each file for its prefix, e.g. sql_agent routes are under /api/sql-agent, settings under /api/settings).')
for path in sorted(glob.glob('backend/routes/*.py')) + ['sql_agent/api/routes.py']:
    try: tree = ast.parse(io.open(path, encoding='utf-8').read())
    except Exception as e: print(f"# {path}: parse error {e}"); continue
    print(f"\n### `{path}`\n\n```")
    for node in ast.walk(tree):
        if not isinstance(node,(ast.FunctionDef, ast.AsyncFunctionDef)): continue
        for dec in node.decorator_list:
            s = ast.unparse(dec)
            m = re.match(r"(?:router|app)\.(get|post|put|patch|delete|websocket)\((['\"])([^'\"]+)", s)
            if not m: continue
            src = ast.unparse(node)
            doc = (ast.get_docstring(node) or '').strip().split('\n')[0][:110]
            writes = 'WRITE' if WRITE.search(src) else 'read'
            audit = ' audit' if re.search(r"audit\(|ChatbotAuditLog|UserAuthorizationAuditLog|_audit", src) else ''
            print(f"{m.group(1).upper():6} {m.group(3):55} {node.name:42} [{writes}{audit}] deps={deps(node)}\n       {doc}")
